repos:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: Run flake8 checks on the code
        entry: pipenv run flake8
        language: python
        types: [python]
        require_serial: true