name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync -d

      - name: Running tests
        env:
          HYPIXEL_KEY: ${{ secrets.HYPIXEL_KEY }}
        run: |
          pipenv run tests
