name: Test Examples

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_examples:
    name: Test Examples
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      id: python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync -d

    - name: Running examples as tests
      env:
        HYPIXEL_KEY: ${{ secrets.HYPIXEL_KEY }}
      run: |
        pipenv run python -m examples.get-guild-data
        pipenv run python -m examples.get-player-data
        pipenv run python -m examples.get-watchdog-stats
        pipenv run python -m examples.normal-caching
        pipenv run python -m examples.user-to-uuid
        pipenv run python -m examples.uuid-to-username
