name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync -d

    - name: Running examples as tests
      env:
        HYPIXEL_KEY: ${{ secrets.HYPIXEL_KEY }}
      run: |
        python -m examples.get-guild-data
        python -m examples.get-player-data
        python -m examples.get-watchdog-stats
        python -m examples.implement-caching
        python -m examples.user-to-uuid
        python -m examples.uuid-to-username
